#数据库配置
spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: wangyu
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #redis配置
  redis:
    port: 6379
    host: 192.168.1.93
    password: 123456
    database: 1

#mybatisplus配置
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wangyu.mysecurity.entity

#日志级别
logging:
  level:
    com.wangyu.mysecurity.mapper: debug

#账户密码加密字符串
AES:
  key: "123999"
