#数据库配置
spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: wangyu
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #redis配置
  redis:
    port: 6379
    host: 192.168.1.93
    password: 123456
    database: 1

#mybatisplus配置
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wangyu.mysecurity.entity

#日志级别
logging:
  level:
    com.wangyu.mysecurity.mapper: debug

#阿里云秘钥
aliyun:
  accessKeyId: xxxxx
  accessKeySecret: xxxxx
  oss:
    #访问域名
    bucket: http://myyayayo.oss-cn-shenzhen.aliyuncs.com/
    #上传域名
    endpoint: http://oss-cn-shenzhen.aliyuncs.com/
    #你的存储空间名称
    bucketName: myyayayo
    #前缀
    urlPrefix: image/

# 七牛云配置
qiniu:
  #你的accessKey
  accessKey: xxxxx
  #你的secretKey
  secretKey: xxxxx
  #你的存储空间名称
  bucket: myyayayo
  #region0 region1 region2 regionNa0 regionAs0
  zone: region0
  #外链默认域名
  domainOfBucket: http://q2xzcsayi.bkt.clouddn.com
  # 链接过期时间，单位是秒，3600代表1小时，-1代表永不过期
  expireInSeconds: -1
  #前缀
  urlPrefix: image/
